.\" genservice.1
.Dd 2018-10-08
.Dt GEncFS 1
.Os
.Sh NAME
.Nm GEncFs
.Nd Simple GUI for EncFs
.Sh SYNOPSIS
.Nm GEncFS
.Op input file
.Sh DESCRIPTION
.Nm genserv
This simple gui lets you mount encrypted file systems, using encfs. 
It is assumed that the encripted filesystem has the directory name .crypt and will be encrypted to the directory crypt in the same directory as .crypt. 
The path to those two directories is stored by GEncFs in a persistant manner. 
For this purpose GEncFS creates the directory ~/.GEncFs.

The program is written in python.
.Sh Command line options
None
.Sh License
As it is
.Sh AUTHOR
Urs Lindegger (urs@linurs.org)
